# Generated by Django 4.1.7 on 2023-03-31 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('delivery_status', models.CharField(blank=True, default='order placed', max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='d_status',
            field=models.CharField(blank=True, default='order_placed', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='d_status_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
