from django.urls import path,include
from . import views


urlpatterns =[
    path('',views.home,name='home'),
    path('merchantlogin', views.MerchantLogin, name='merchantlogin'),
    path('merchantsignup', views.Merchantsignup, name='merchantsignup'),
    path('Merchant_home', views.Merchant_home, name='Merchant_home'),
    path('CreateProduct',views.CreateProduct,name='CreateProduct'),
    path('ProductDetails/<int:id>',views.ProductDetails,name='ProductDetails'),
    path('Product_update/<int:id>', views.Product_update, name='Product_update'),
    path('Product_delete/<int:id>', views.Product_delete, name='Product_delete'),
    path('LogoutMerchant', views.LogoutMerchant, name='LogoutMerchant'),
    path('merchant_profile_view',views.merchant_profile_view,name='merchant_profile_view'),
    path('Merchant_profile_update/<int:pk>',views.Merchant_profile_update,name='Merchant_profile_update'),
    path('Costomer_signup',views.Costomer_signup,name='Costomer_signup'),
    path('CostomerLogin', views.CostomerLogin, name='CostomerLogin'),
    path('Costomer_home', views.Costomer_home, name='Costomer_home'),
    path('Product_merchant_Details/<int:id>',views.Product_merchant_Details,name='Product_merchant_Details'),
    path('delivery_details/<int:id>/<int:pk>',views.delivery_details,name='delivery_details'),
    path('Costomer_orders',views.Costomer_orders,name='Costomer_orders'),
    path('Costomer_update/<int:pk>',views.Costomer_update,name='Costomer_update'),
    path('costomer_profile_view',views.costomer_profile_view,name='costomer_profile_view'),
    path('LogoutCostomer',views.LogoutCostomer,name='LogoutCostomer'),
    path('Aboutas', views.Aboutas, name='Aboutas'),
    path('Merchant_orders',views.Merchant_orders,name='Merchant_orders'),
    path('manage_order',views.manage_order,name='manage_order'),
    path('delivered/<int:id>',views.delivered,name='delivered'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('admintLogin',views.admintLogin,name='admintLogin'),
    path('Poducts_list/', views.Poducts_list, name='Poducts_list'),
    path('admin_product_Details/<int:id>',views.admin_product_Details,name='admin_product_Details'),
    path('delete_admn_product/<int:id>',views.delete_admn_product,name='delete_admn_product'),
    path('merchant_list',views.merchant_list,name='merchant_list'),
    path('costomer_list', views.costomer_list, name='costomer_list'),
    path('order_list', views.order_list, name='order_list'),
    path('Helpview', views.Helpview, name='Helpview'),
    path('Helpsend', views.Helpsend, name='Helpsend'),
    path('costomer_delete/<int:pk>',views.costomer_delete,name='costomer_delete'),
    path('merchant_delete/<int:pk>',views.merchant_delete,name='merchant_delete'),
    path('Logoutadmin',views.Logoutadmin,name='Logoutadmin'),
    path('Costmer_order_cancel/<int:id>', views.Costmer_order_cancel, name='Costmer_order_cancel'),
    path('delivery_status_update/<int:id>',views.delivery_status_update,name='delivery_status_update'),
    path('order_track/<int:id>',views.order_track,name='order_track')
]